colors implementations, reviwer

diff --git a/.github/workflows/pmd.yml b/.github/workflows/pmd.yml
--- a/.github/workflows/pmd.yml
+++ b/.github/workflows/pmd.yml
@@ -38,8 +38,14 @@ jobs:
 
     - name: Ejecutar PMD
       run: |
-        cd pmd/pmd-bin-7.0.0-rc3/bin
-        ./pmd check -d ../../../src/main/java -R ../../../pmdrules/rulesets/java/gardian.xml -f text
+        output=$(./pmd check -d ../../../src/main/java -R ../../../pmdrules/rulesets/java/gardian.xml -f text)
+        echo "$output"
+        if echo "$output" | grep -q "ParseException"; then
+          echo -e "\e[91mFAILED\e[0mPMD encontró un ParseException en la salida."
+          exit 1
+        else
+          echo -e "\e[91mACCEPT\e[0mPMD no encontró un ParseException en la salida."
+        fi
 
     - name: Guardar caché de PMD
       if: steps.cache-check.outputs.cache-hit != 'true'
