test whit errors code ;

diff --git a/.github/workflows/pmd.yml b/.github/workflows/pmd.yml
--- a/.github/workflows/pmd.yml
+++ b/.github/workflows/pmd.yml
@@ -40,7 +40,7 @@ jobs:
       run: |
         cd pmd/pmd-bin-7.0.0-rc3/bin
         output=$(./pmd check -d ../../../src/main/java -R ../../../pmdrules/rulesets/java/gardian.xml -f text)
-        if echo "$output" | grep -q "ERROR"; then
+        if echo "$output" | grep -q "ERROR" || echo "$output" | grep -q "ParseException" ; then
           echo -e "\e[1;31mFAILED\e[0m PMD encontró un errores en tu codigo."
           exit 1
         else
